import type { Metadata } from "next";
import { Geist, Geist_Mono, Quicksand } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/components/cart-provider";

const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-quicksand",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${quicksand.variable} h-full antialiased`}>
      <body className="min-h-screen bg-[#F9F6F0] flex justify-center m-0 font-sans font-medium">
        <CartProvider>
          <div className="w-full max-w-md min-h-screen bg-white relative pb-24 shadow-sm">
            {children}
          </div>
        </CartProvider>
      </body>
    </html>
  );
}
